export type PortfolioProject = {
  name: string;
  slug: string;
  category: string;
  tag: string;
  filters: string[];
  platform: string;
  image: string;
  year: string;
  featured?: boolean;
  industry: string;
  summary: string;
  challenge: string;
  approach: string;
  outcome: string;
  services: string[];
  accent: string;
  gallery: string[];
  /** Tall full-page screenshot used for the scroll-on-hover hero preview. */
  fullPage?: string;
  /** Live domain shown in the browser-frame address bar. */
  liveUrl?: string;
};

export const portfolioProjects: PortfolioProject[] = [
  {
    name: "Care Partners Australia",
    slug: "care-partners-australia",
    category: "Web Design · Branding · UI/UX",
    tag: "NDIS Provider",
    filters: ["Web Design", "Branding", "UI/UX"],
    platform: "Next.js · Figma",
    image: "/portfolio/Care-Partners-bbnn.png",
    year: "2024",
    featured: true,
    industry: "Health and disability support",
    summary: "A clearer digital home for a multicultural care provider, built around trust, speed, accessibility, and simple service discovery.",
    challenge: "Care Partners needed a digital presence that felt credible and easy to understand for participants, families, and referral partners.",
    approach: "We rebuilt the brand and website around calmer messaging, direct pathways, accessible content structure, and a custom front end.",
    outcome: "The final experience presents the organisation with more confidence, makes core services easier to scan, and gives the team a stronger platform for growth.",
    services: ["Logo design", "Website design", "UI/UX", "Next.js development"],
    accent: "#E01B24",
    gallery: ["/portfolio/cpa/Scene-2.png", "/portfolio/cpa/ghyt.jpg"],
    fullPage: "/portfolio/care-partners-fullpage.png",
    liveUrl: "carepartnersau.com.au",
  },
  {
    name: "Australian Ghanaian Chamber of Commerce",
    slug: "australian-ghanaian-chamber-of-commerce",
    category: "Web Design · Branding",
    tag: "Commerce",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/AGCCI.png",
    year: "2024",
    industry: "Business and trade",
    summary: "A polished chamber website designed to communicate authority, membership value, and cross-market business opportunity.",
    challenge: "The chamber needed a more structured web presence that could support advocacy, events, member engagement, and business development.",
    approach: "We used a confident editorial layout, strong content hierarchy, and flexible WordPress sections to make the organisation easier to understand.",
    outcome: "The new site gives AGCCI a more professional platform for stakeholders, members, and partners across Australia and Ghana.",
    services: ["Website design", "WordPress build", "Content structure", "Brand presentation"],
    accent: "#D8A21D",
    gallery: ["/portfolio/AGCCI-99.png", "/portfolio/AGCCI.png"],
  },
  {
    name: "WINSTAMAC",
    slug: "winstamac",
    category: "Brand Strategy · UI/UX",
    tag: "Brand",
    filters: ["Branding", "UI/UX"],
    platform: "Figma",
    image: "/portfolio/Winstamac-Portfolio-Cover.avif",
    year: "2024",
    industry: "Real estate technology",
    summary: "A premium visual and interface direction for a property platform, balancing product clarity with aspirational market positioning.",
    challenge: "WINSTAMAC needed a brand and interface system that could make property browsing feel trustworthy, modern, and easy to compare.",
    approach: "We shaped a crisp UI language, marketplace-style screens, and a visual system that could carry both listings and brand communications.",
    outcome: "The result is a sharper product story with a more refined customer-facing experience and stronger visual consistency.",
    services: ["Brand strategy", "UI design", "Product direction", "Design system"],
    accent: "#F0712F",
    gallery: ["/portfolio/WINSTAMAC.png", "/portfolio/Winstamac-Portfolio-Cover-3.avif"],
    fullPage: "/portfolio/winstamac-fullpage.png",
    liveUrl: "winstamac.com",
  },
  {
    name: "Sababa Global",
    slug: "sababa-global",
    category: "Brand Strategy · UX",
    tag: "Global",
    filters: ["Branding", "UI/UX"],
    platform: "Figma",
    image: "/portfolio/Saba-Mock.png",
    year: "2023",
    industry: "Global services",
    summary: "A refined brand and digital direction built to help an international business feel more cohesive across touchpoints.",
    challenge: "The brand needed a stronger digital language that could feel global without becoming generic.",
    approach: "We developed a visual direction, UX structure, and presentation system with clear hierarchy and flexible brand moments.",
    outcome: "Sababa Global gained a more consistent foundation for campaigns, web pages, and customer-facing materials.",
    services: ["Brand direction", "UX structure", "Visual design", "Campaign assets"],
    accent: "#7C5CFF",
    gallery: ["/portfolio/Sababa-33-scaled.jpg", "/portfolio/Saba-Mock.png"],
    fullPage: "/portfolio/sababa-fullpage.png",
    liveUrl: "sababaservices.com",
  },
  {
    name: "Viride Energy Africa",
    slug: "viride-energy-africa",
    category: "Web Design · Development",
    tag: "Energy",
    filters: ["Web Design"],
    platform: "React.js",
    image: "/portfolio/webgaze_viride-energy.webp",
    year: "2024",
    industry: "Renewable energy",
    summary: "A modern energy-sector web presence created to explain capability, market focus, and sustainability credentials with clarity.",
    challenge: "Viride needed a website that could carry technical credibility while staying approachable to investors, partners, and customers.",
    approach: "We built a clean page system with strong section rhythm, direct messaging, and visual cues connected to energy and infrastructure.",
    outcome: "The site now frames Viride as a serious, future-focused operator with a clearer story for multiple audiences.",
    services: ["Website design", "React development", "Content hierarchy", "Visual direction"],
    accent: "#2CB56E",
    gallery: ["/portfolio/webgaze_viride-energy.webp", "/portfolio/Building-front.webp"],
  },
  {
    name: "Ben Ari Accounting",
    slug: "ben-ari-accounting",
    category: "Web Design · Product Design",
    tag: "Accounting",
    filters: ["Web Design", "UI/UX"],
    platform: "WordPress",
    image: "/portfolio/Ben-Ari.jpg",
    year: "2023",
    industry: "Accounting and advisory",
    summary: "A professional services website designed to feel calm, direct, and credible for small business accounting clients.",
    challenge: "The practice needed a stronger online presence that made services and enquiry pathways easier to understand.",
    approach: "We focused on clear service packaging, restrained visual styling, and a structure that reduces friction for prospective clients.",
    outcome: "The final site gives the firm a cleaner first impression and a more practical platform for enquiries.",
    services: ["Website design", "WordPress build", "Service messaging", "Lead pathways"],
    accent: "#4169E1",
    gallery: ["/portfolio/Ben-Ari.jpg", "/portfolio/kkjjhh-1.webp"],
  },
  {
    name: "PhytoScience Australia",
    slug: "phytoscience-australia",
    category: "Web Design · Branding",
    tag: "Health",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/PhytoScience-Au2.webp",
    year: "2024",
    industry: "Health and wellness",
    summary: "A cleaner wellness brand experience designed to make product education and customer confidence easier.",
    challenge: "PhytoScience needed digital presentation that felt more considered while supporting product-led browsing.",
    approach: "We organised content around trust, product clarity, visual consistency, and a simpler path through the site.",
    outcome: "The updated experience feels more credible and easier to navigate for customers exploring the brand.",
    services: ["Website design", "Brand presentation", "WordPress build", "Product content"],
    accent: "#58A64E",
    gallery: ["/portfolio/PhytoScience-Au2.webp", "/portfolio/gghb.png"],
  },
  {
    name: "Petra Care Services",
    slug: "petra-care-services",
    category: "Web Design · UI/UX",
    tag: "Care",
    filters: ["Web Design", "UI/UX"],
    platform: "WordPress",
    image: "/portfolio/Petra-Care.webp",
    year: "2024",
    industry: "Community care",
    summary: "A service-led care website shaped around warmth, clarity, and simple next steps for families and participants.",
    challenge: "Petra Care needed to explain services in a way that felt human, trustworthy, and easy to act on.",
    approach: "We created a softer visual system, simplified service pages, and placed enquiry actions where users naturally need them.",
    outcome: "The site now gives visitors clearer information and a more confident route to making contact.",
    services: ["Website design", "UI/UX", "WordPress build", "Service structure"],
    accent: "#E86A6A",
    gallery: ["/portfolio/Petra-Care.webp", "/portfolio/Scene-2.png"],
  },
  {
    name: "Onboard Plumbing",
    slug: "onboard-plumbing",
    category: "Web Design · Branding",
    tag: "Trades",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/Onboard.jpg",
    year: "2023",
    industry: "Trades and local services",
    summary: "A practical trade website built to make services obvious, calls to action immediate, and the business look established.",
    challenge: "Onboard needed a digital presence that could compete locally and turn urgent service visits into enquiries.",
    approach: "We paired direct service messaging with a no-fuss layout, strong contact cues, and a brand treatment suited to the trade category.",
    outcome: "The site gives customers a faster path to understanding services and contacting the team.",
    services: ["Website design", "Branding", "WordPress build", "Local service UX"],
    accent: "#1A8FBF",
    gallery: ["/portfolio/Onboard.jpg", "/portfolio/hghgmn.png"],
  },
  {
    name: "Janny Global",
    slug: "janny-global",
    category: "Web Design · Mobile UI",
    tag: "Real Estate",
    filters: ["Web Design", "UI/UX"],
    platform: "React.js",
    image: "/portfolio/Janny-global-mobile.webp",
    year: "2024",
    industry: "Property and real estate",
    summary: "A mobile-first real estate experience designed around property discovery, scanning, and confident enquiry behaviour.",
    challenge: "The product needed a cleaner mobile direction for browsing property content without overwhelming users.",
    approach: "We created focused mobile screens, simplified listing information, and a responsive design language for future expansion.",
    outcome: "The interface feels sharper, more usable, and better prepared for product iteration.",
    services: ["Mobile UI", "Website design", "React development", "UX strategy"],
    accent: "#E8792E",
    gallery: ["/portfolio/Janny-global-mobile.webp", "/portfolio/WINSTAMAC.png"],
  },
  {
    name: "DownUnder Radio",
    slug: "downunder-radio",
    category: "Web Design · Branding",
    tag: "Media",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/DownUnder-Radio-scaled.jpg",
    year: "2023",
    industry: "Media and entertainment",
    summary: "A lively media website built to support shows, community updates, and audience engagement.",
    challenge: "The station needed a more flexible web presence for content, programming, and community communication.",
    approach: "We designed a bolder content structure with strong media cues and WordPress management for regular updates.",
    outcome: "The site gives the brand a more energetic home and makes it easier to surface current programming and announcements.",
    services: ["Website design", "Brand presentation", "WordPress build", "Content system"],
    accent: "#E3342F",
    gallery: ["/portfolio/DownUnder-Radio-scaled.jpg", "/portfolio/jjkkkll.jpg"],
  },
  {
    name: "Salaka Dance Ensemble",
    slug: "salaka-dance-ensemble",
    category: "Web Design · Branding",
    tag: "Arts",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/Salaka-Dance-scaled.webp",
    year: "2023",
    industry: "Arts and culture",
    summary: "A cultural arts website designed to feel expressive while keeping performances, identity, and enquiries easy to access.",
    challenge: "Salaka needed a web presence that carried movement and personality without losing practical clarity.",
    approach: "We blended expressive imagery with a simple structure for performances, organisation information, and contact pathways.",
    outcome: "The finished site feels more vivid and easier to use for event organisers, audiences, and collaborators.",
    services: ["Website design", "Branding", "WordPress build", "Content structure"],
    accent: "#C9822B",
    gallery: ["/portfolio/Salaka-Dance-scaled.webp", "/portfolio/004-Wall-Sign-Logo-Mockup_-scaled.jpg"],
  },
];

export const projectFilters = ["All", "Web Design", "Branding", "UI/UX"];

export function getProject(slug: string) {
  return portfolioProjects.find((project) => project.slug === slug);
}
