export type PortfolioProject = {
  name: string;
  slug: string;
  category: string;
  tag: string;
  filters: string[];
  platform: string;
  image: string;
  year: string;
  featured?: boolean;
  industry: string;
  summary: string;
  challenge: string;
  approach: string;
  outcome: string;
  services: string[];
  accent: string;
  gallery: string[];
  /** Tall full-page screenshot used for the scroll-on-hover hero preview. */
  fullPage?: string;
  /** Live domain shown in the browser-frame address bar. */
  liveUrl?: string;
};

export const portfolioProjects: PortfolioProject[] = [
  {
    name: "Care Partners Australia",
    slug: "care-partners-australia",
    category: "Web Design · Branding · UI/UX",
    tag: "NDIS Provider",
    filters: ["Web Design", "Branding", "UI/UX"],
    platform: "Next.js · Figma",
    image: "/portfolio/care-partners-australia-cover.jpg",
    year: "2024",
    featured: true,
    industry: "Health and disability support",
    summary: "A clearer digital home for a multicultural care provider, built around trust, speed, accessibility, and simple service discovery.",
    challenge: "Care Partners needed a digital presence that felt credible and easy to understand for participants, families, and referral partners.",
    approach: "We rebuilt the brand and website around calmer messaging, direct pathways, accessible content structure, and a custom front end.",
    outcome: "The final experience presents the organisation with more confidence, makes core services easier to scan, and gives the team a stronger platform for growth.",
    services: ["Logo design", "Website design", "UI/UX", "Next.js development"],
    accent: "#E01B24",
    gallery: ["/portfolio/cpa/care-partners-australia-gallery-1.webp", "/portfolio/cpa/care-partners-australia-gallery-2.jpg"],
    fullPage: "/portfolio/cpa/care-partners-australia-homepage-fullpage.webp",
    liveUrl: "carepartnersau.com.au",
  },
  {
    name: "Australian Ghanaian Chamber of Commerce",
    slug: "australian-ghanaian-chamber-of-commerce",
    category: "Web Design · Branding",
    tag: "Commerce",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/australian-ghanaian-chamber-of-commerce-cover.jpg",
    year: "2024",
    industry: "Business and trade",
    summary: "A polished chamber website designed to communicate authority, membership value, and cross-market business opportunity.",
    challenge: "The chamber needed a more structured web presence that could support advocacy, events, member engagement, and business development.",
    approach: "We used a confident editorial layout, strong content hierarchy, and flexible WordPress sections to make the organisation easier to understand.",
    outcome: "The new site gives AGCCI a more professional platform for stakeholders, members, and partners across Australia and Ghana.",
    services: ["Website design", "WordPress build", "Content structure", "Brand presentation"],
    accent: "#D8A21D",
    gallery: ["/portfolio/australian-ghanaian-chamber-of-commerce-gallery.webp", "/portfolio/australian-ghanaian-chamber-of-commerce-cover.jpg"],
    fullPage: "/portfolio/australian-ghanaian-chamber-of-commerce-homepage-fullpage.jpg",
    liveUrl: "agcci.org.au",
  },
  {
    name: "WINSTAMAC",
    slug: "winstamac",
    category: "Web Design · UI/UX",
    tag: "House Plans",
    filters: ["Web Design", "UI/UX"],
    platform: "WordPress",
    image: "/portfolio/winstamac-cover.webp",
    year: "2024",
    industry: "Architecture · House plans",
    summary: "An on-demand house-plan marketplace — searchable 3D designs with real specs, video walkthroughs, and cost-of-build pricing, clear on any screen.",
    challenge: "World-class 3D house designs sold through a flat, template-feeling site that buried the catalogue and made browsing and pricing a chore.",
    approach: "We led with the architecture: a searchable plan marketplace, full property pages with specs and video tours, transparent pricing, and a fast mobile path.",
    outcome: "A storefront that finally sells the designs — easy to search, compare, and buy, for home-builders anywhere in the world.",
    services: ["Website design", "House-plan marketplace", "UI/UX", "WordPress build"],
    accent: "#F0712F",
    gallery: ["/portfolio/winstamac-cover.webp", "/portfolio/winstamac-gallery.avif"],
    fullPage: "/portfolio/winstamac/live/winstamac-homepage-fullpage.jpg",
    liveUrl: "winstamac.com",
  },
  {
    name: "Sababa Global Trade & Logistics",
    slug: "sababa-global",
    category: "Web Design · Branding",
    tag: "Logistics",
    filters: ["Web Design", "Branding", "UI/UX"],
    platform: "WordPress",
    image: "/portfolio/sababa-global-cover.webp",
    year: "2024",
    industry: "Freight forwarding & logistics",
    summary: "A confident digital home for an international freight forwarder — door-to-door services made clear, with every freight mode and customs offering easy to find and act on.",
    challenge: "A true international freight forwarder with deep customs expertise, but a web presence that didn't carry the scale, range, or reassurance the business delivers in practice.",
    approach: "We led with the promise — safe passage and timely delivery — then gave each freight mode and customs service its own clear page, with quote and contact paths never more than a tap away.",
    outcome: "A site that reads like a serious global operator: clear services, credible tone, and a faster route from visitor to enquiry across desktop and mobile.",
    services: ["Website design", "WordPress build", "UI/UX", "Brand presentation"],
    accent: "#15728C",
    gallery: ["/portfolio/sababa-global-gallery.jpg", "/portfolio/sababa-global-cover.webp"],
    fullPage: "/portfolio/sababa/live/sababa-global-homepage-fullpage.jpg",
    liveUrl: "sababaservices.com",
  },
  {
    name: "Viride Energy Africa",
    slug: "viride-energy-africa",
    category: "Web Design · Development",
    tag: "Energy",
    filters: ["Web Design"],
    platform: "React.js",
    image: "/portfolio/viride-energy-africa-cover.webp",
    year: "2024",
    industry: "Renewable energy",
    summary: "A modern energy-sector web presence created to explain capability, market focus, and sustainability credentials with clarity.",
    challenge: "Viride needed a website that could carry technical credibility while staying approachable to investors, partners, and customers.",
    approach: "We built a clean page system with strong section rhythm, direct messaging, and visual cues connected to energy and infrastructure.",
    outcome: "The site now frames Viride as a serious, future-focused operator with a clearer story for multiple audiences.",
    services: ["Website design", "React development", "Content hierarchy", "Visual direction"],
    accent: "#2CB56E",
    gallery: ["/portfolio/viride-energy-africa/live/viride-energy-africa-services.jpg", "/portfolio/viride-energy-africa/live/viride-energy-africa-about.jpg"],
    fullPage: "/portfolio/viride-energy-africa/live/viride-energy-africa-homepage-fullpage.jpg",
    liveUrl: "viridenergy.com",
  },
  {
    name: "Ben Ari Accounting",
    slug: "ben-ari-accounting",
    category: "Web Design · Product Design",
    tag: "Accounting",
    filters: ["Web Design", "UI/UX"],
    platform: "WordPress",
    image: "/portfolio/ben-ari-accounting-cover.jpg",
    year: "2023",
    industry: "Accounting and advisory",
    summary: "A professional services website designed to feel calm, direct, and credible for small business accounting clients.",
    challenge: "The practice needed a stronger online presence that made services and enquiry pathways easier to understand.",
    approach: "We focused on clear service packaging, restrained visual styling, and a structure that reduces friction for prospective clients.",
    outcome: "The final site gives the firm a cleaner first impression and a more practical platform for enquiries.",
    services: ["Website design", "WordPress build", "Service messaging", "Lead pathways"],
    accent: "#4169E1",
    gallery: ["/portfolio/ben-ari-accounting-cover.jpg", "/portfolio/ben-ari-accounting-gallery.webp"],
  },
  {
    name: "PhytoScience Australia",
    slug: "phytoscience-australia",
    category: "Web Design · Branding",
    tag: "Health",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/phytoscience-australia-cover.webp",
    year: "2024",
    industry: "Health and wellness",
    summary: "A cleaner wellness brand experience designed to make product education and customer confidence easier.",
    challenge: "PhytoScience needed digital presentation that felt more considered while supporting product-led browsing.",
    approach: "We organised content around trust, product clarity, visual consistency, and a simpler path through the site.",
    outcome: "The updated experience feels more credible and easier to navigate for customers exploring the brand.",
    services: ["Website design", "Brand presentation", "WordPress build", "Product content"],
    accent: "#58A64E",
    gallery: ["/portfolio/phyto/live/phytoscience-australia-services.jpg", "/portfolio/phyto/live/phytoscience-australia-about.jpg"],
    fullPage: "/portfolio/phyto/live/phytoscience-australia-homepage-fullpage.jpg",
    liveUrl: "phytoscienceaustralia.com.au",
  },
  {
    name: "Petra Care Services",
    slug: "petra-care-services",
    category: "Web Design · UI/UX",
    tag: "Care",
    filters: ["Web Design", "UI/UX"],
    platform: "WordPress",
    image: "/portfolio/petra-care-services-cover.webp",
    year: "2024",
    industry: "Community care",
    summary: "A service-led care website shaped around warmth, clarity, and simple next steps for families and participants.",
    challenge: "Petra Care needed to explain services in a way that felt human, trustworthy, and easy to act on.",
    approach: "We created a softer visual system, simplified service pages, and placed enquiry actions where users naturally need them.",
    outcome: "The site now gives visitors clearer information and a more confident route to making contact.",
    services: ["Website design", "UI/UX", "WordPress build", "Service structure"],
    accent: "#E86A6A",
    gallery: ["/portfolio/petra-care-services/live/petra-care-services-services.jpg", "/portfolio/petra-care-services/live/petra-care-services-about.jpg"],
    fullPage: "/portfolio/petra-care-services/live/petra-care-services-homepage-fullpage.jpg",
    liveUrl: "petracare.com.au",
  },
  {
    name: "Onboard Plumbing",
    slug: "onboard-plumbing",
    category: "Web Design · Branding",
    tag: "Trades",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/onboard-plumbing-cover.jpg",
    year: "2023",
    industry: "Trades and local services",
    summary: "A practical trade website built to make services obvious, calls to action immediate, and the business look established.",
    challenge: "Onboard needed a digital presence that could compete locally and turn urgent service visits into enquiries.",
    approach: "We paired direct service messaging with a no-fuss layout, strong contact cues, and a brand treatment suited to the trade category.",
    outcome: "The site gives customers a faster path to understanding services and contacting the team.",
    services: ["Website design", "Branding", "WordPress build", "Local service UX"],
    accent: "#1A8FBF",
    gallery: ["/portfolio/onboard-plumbing/live/onboard-plumbing-services.jpg", "/portfolio/onboard-plumbing/live/onboard-plumbing-about.jpg"],
    fullPage: "/portfolio/onboard-plumbing/live/onboard-plumbing-homepage-fullpage.jpg",
    liveUrl: "onboardplumbing.com.au",
  },
  {
    name: "Janny Global",
    slug: "janny-global",
    category: "Web Design · Mobile UI",
    tag: "Real Estate",
    filters: ["Web Design", "UI/UX"],
    platform: "React.js",
    image: "/portfolio/janny-global-cover.webp",
    year: "2024",
    industry: "Property and real estate",
    summary: "A mobile-first real estate experience designed around property discovery, scanning, and confident enquiry behaviour.",
    challenge: "The product needed a cleaner mobile direction for browsing property content without overwhelming users.",
    approach: "We created focused mobile screens, simplified listing information, and a responsive design language for future expansion.",
    outcome: "The interface feels sharper, more usable, and better prepared for product iteration.",
    services: ["Mobile UI", "Website design", "React development", "UX strategy"],
    accent: "#E8792E",
    gallery: ["/portfolio/janny-global/live/janny-global-services.jpg", "/portfolio/janny-global/live/janny-global-about.jpg"],
    fullPage: "/portfolio/janny-global/live/janny-global-homepage-fullpage.jpg",
    liveUrl: "jannyglobal.com",
  },
  {
    name: "DownUnder Radio",
    slug: "downunder-radio",
    category: "Web Design · Branding",
    tag: "Media",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/downunder-radio-cover.jpg",
    year: "2023",
    industry: "Media and entertainment",
    summary: "A lively media website built to support shows, community updates, and audience engagement.",
    challenge: "The station needed a more flexible web presence for content, programming, and community communication.",
    approach: "We designed a bolder content structure with strong media cues and WordPress management for regular updates.",
    outcome: "The site gives the brand a more energetic home and makes it easier to surface current programming and announcements.",
    services: ["Website design", "Brand presentation", "WordPress build", "Content system"],
    accent: "#E3342F",
    gallery: ["/portfolio/downunder-radio-cover.jpg", "/portfolio/downunder-radio-gallery.jpg"],
  },
  {
    name: "Salaka Dance Ensemble",
    slug: "salaka-dance-ensemble",
    category: "Web Design · Branding",
    tag: "Arts",
    filters: ["Web Design", "Branding"],
    platform: "WordPress",
    image: "/portfolio/salaka-dance-ensemble-cover.webp",
    year: "2023",
    industry: "Performing arts · African culture",
    summary: "Ghana's celebrated drumming and dance ensemble, online with the colour and movement of the stage — story, every service, and bookings one tap away.",
    challenge: "Decades of acclaim — performing for heads of state, leading Ghana's independence celebrations — with no home online that carried the energy.",
    approach: "We let the performance lead: vivid imagery, a clear spine through their story and four service lines, and a booking path that never gets lost.",
    outcome: "A site as alive as the ensemble — easy for event organisers, audiences, and partners worldwide to explore and book.",
    services: ["Website design", "Branding", "WordPress build", "Content structure"],
    accent: "#C9822B",
    gallery: ["/portfolio/salaka-dance-ensemble-cover.webp", "/portfolio/salaka-dance-ensemble-gallery.jpg"],
    fullPage: "/portfolio/salaka/live/salaka-dance-ensemble-homepage-fullpage.jpg",
    liveUrl: "salakadance.org",
  },
];

export const projectFilters = ["All", "Web Design", "Branding", "UI/UX"];

export function getProject(slug: string) {
  return portfolioProjects.find((project) => project.slug === slug);
}
